[package]
name = "saty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dimacs = "0.2.0"
log = {version="0.4.17", features=["max_level_info"]}
simplelog = "0.12.0"
